W7D1/99catsPart2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resource :session, only: [:new, :create, :destroy]
  resource :users, only: [:new, :create]

  root to: redirect('/cats')
end

W7D1/99catsPart2/app/models/user.rb
class User < ApplicationRecord
    validates :user_name, presence: true, uniqueness: true
    validates :password_digest, presence: {message: "Password can't be blank"}
    validates :session_token, presence: true
    validates :password, length: {minimum: 6, allow_nil: true}
    #before_validation :ensure_session_token
    after_initialize :ensure_session_token
    
    has_many :cats,
    foreign_key: :user_id,
    class_name: :Cat
    
    attr_reader :password

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password) 
    end

    def self.find_by_credentials(user_name, password)
        user = User.find_by(user_name: user_name)
        return user if user && user.is_password?(password)
        nil
    end

    private

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end
end

W7D1/99catsPart2/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_out, only: [:create]

    def index
        @users = User.all
        render json: @users
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login_user!(@user)
            redirect_to users_url(@user)
        else
            render json: @user.errors.full_messages, status: 422
        end
    end

    def new
        @user = User.new
        render :new
    end


    private

    def user_params
        params.require(:user).permit(:user_name, :password)
    end
end

W7D1/99catsPart2/app/views/users/_user.html.erb
<ul>
  <li>username: <%= user.username %></li>
  <li>email: <%= user.email %></li>
  <li>age: <%= user.age %></li>
  <li>coding affiliation: <%= user.coding_affiliation %></li>
  <li><%= link_to 'Edit User', edit_user_url(user) %></li>
  <li><%= button_to 'Delete User', user_url(user), method: :delete %></li>
  <form action="<%= user_url(user) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <button type="submit">Delete User2</button>
  </form>
</ul>

<% if action == :show %>
  <li><a href=<%= users_url %>>User Index Page</a></li>
  <% else %>
    <li><a href=<%= user_url(user) %>>User Show Page</a></li>
<% end%>

W7D1/99catsPart2/app/views/users/edit.html.erb
<!-- method: attribute in the form tag will need to be overwritten because we need to do a patch request-->
<!-- action: attribute that will route our date and will need a wildcard-->

<!-- input type "hidden": users will not see this input tag on the page-->
<!-- name="_method": this is the synta to overwrite the method attribute for the form tag-->
<!-- value="PATCH" the HTTP verb that we want instead-->

<form action="<%= user_url(@user) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <label for="username">Username</label>
  <input type="text" id="username" name="user[username]" value="<%= @user.username %>">

  <br>

  <label>Email:
  <input type="text" name="user[email]" value="<%= @user.email %>">
  </label>

  <br>

   <label>Age:
  <input type="text" name="user[age]" value="<%= @user.age %>">
  </label>

  <br>

   <label>Coding Affiliation:
  <input type="text" name="user[coding_affiliation]" value="<%= @user.coding_affiliation %>">
  </label>


  <input type="submit" value="Update User">


</form>

W7D1/99catsPart2/app/views/users/index.html.erb
<h1>All the users!</h1>
<a href="<%= new_user_url  %>">Create a User</a>
<ul>
  <% @users.each do |user|%>
    <li>
      <%= render 'user', user: user, action: :index %>
    </li>
  <%end%>

</ul>

W7D1/99catsPart2/app/views/users/new.html.erb
<!-- action: url or rails route to which we want to send our form data-->
<!-- method: http method or verb that we want to use and only accepts GET or POST -->

<!-- for: used in the label tag and must be the same as the input tag's id attribute -->
<!-- name: how the data is named when passed through and will point to value returned within params -->

<form action="<%=users_url %>" method="POST">

  <label for="user_name">Username</label>
  <input type="text" id="user_name" name="user[user_name]" value="<%= @user.user_name %>">

  <br>

  <label>Password:
  <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Create User">


</form>

W7D1/99catsPart2/app/views/users/show.html.erb
<h1>User Show Page</h1>
<%= render 'user', user: @user, action: :show %>